import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./markdown.css";
import "./globals.css";
import AuthCard from "./(home)/components/AuthCard";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="flex justify-between">
        <div></div>
        <AuthCard />
      </header>
      <body className={`${montserrat.variable} antialiased`}>{children}</body>
    </html>
  );
}
